Soletta: LWM2M
LWM2M
Communication Modules
Routines that handle LWM2M protocol.
Data Structures
struct sol_lwm2m_client
A handle to a LWM2M client.
struct sol_lwm2m_client_info
A handle that contains information about a registered LWM2M client.
struct sol_lwm2m_client_object
A handle of a client's object.
struct sol_lwm2m_client_object_instance
A handle that contains information about a client object instance.
struct sol_lwm2m_object
A LWM2M object implementation.
struct sol_lwm2m_resource
Struct that represents an LWM2M resource.
struct sol_lwm2m_server
A handle to a LWM2M server.
struct sol_lwm2m_tlv
Struct that represents TLV data.
Macros
#define SOL_LWM2M_DEFAULT_SERVER_PORT (5683)
Macro that defines the default port for a LWM2M server.
#define SOL_LWM2M_RESOURCE_INIT(ret_value_, resource_, id_, resource_len_, data_type_,...)
Convinent macro to initialize a LWM2M resource.
Typedefs
typedef void(* sol_lwm2m_server_content_cb)(void *data, struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *client, const char *path, sol_coap_responsecode_t response_code, enum sol_lwm2m_content_type content_type, struct sol_str_slice content)
Callback used to inform a observable/read response.
typedef void(* sol_lwm2m_server_management_status_response_cb)(void *data, struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *client, const char *path, sol_coap_responsecode_t response_code)
Callback used to inform create/write/execute/delete response.
typedef void(* sol_lwm2m_server_registration_event_cb)(void *data, struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *cinfo, enum sol_lwm2m_registration_event event)
Callback that is used to inform a LWM2M client registration event.
Enumerations
enum sol_lwm2m_binding_mode {
SOL_LWM2M_BINDING_MODE_U, SOL_LWM2M_BINDING_MODE_UQ, SOL_LWM2M_BINDING_MODE_S, SOL_LWM2M_BINDING_MODE_SQ,
SOL_LWM2M_BINDING_MODE_US, SOL_LWM2M_BINDING_MODE_UQS, SOL_LWM2M_BINDING_MODE_UNKNOWN = -1
}
LWM2M Client binding mode.
enum sol_lwm2m_content_type { SOL_LWM2M_CONTENT_TYPE_TEXT = 1541, SOL_LWM2M_CONTENT_TYPE_OPAQUE = 1544, SOL_LWM2M_CONTENT_TYPE_TLV = 1542, SOL_LWM2M_CONTENT_TYPE_JSON = 1543 }
Enum that represent a LWM2M response/request content type.
enum sol_lwm2m_registration_event { SOL_LWM2M_REGISTRATION_EVENT_REGISTER, SOL_LWM2M_REGISTRATION_EVENT_UPDATE, SOL_LWM2M_REGISTRATION_EVENT_UNREGISTER, SOL_LWM2M_REGISTRATION_EVENT_TIMEOUT }
Enum that express a LWM2M client lifecycle changes.
enum sol_lwm2m_resource_data_type {
SOL_LWM2M_RESOURCE_DATA_TYPE_STRING, SOL_LWM2M_RESOURCE_DATA_TYPE_INT, SOL_LWM2M_RESOURCE_DATA_TYPE_FLOAT, SOL_LWM2M_RESOURCE_DATA_TYPE_BOOLEAN,
SOL_LWM2M_RESOURCE_DATA_TYPE_OPAQUE, SOL_LWM2M_RESOURCE_DATA_TYPE_TIME, SOL_LWM2M_RESOURCE_DATA_TYPE_OBJ_LINK, SOL_LWM2M_RESOURCE_DATA_TYPE_NONE = -1
}
Enum that represents an LWM2M resource data type.
enum sol_lwm2m_resource_type { SOL_LWM2M_RESOURCE_TYPE_SINGLE, SOL_LWM2M_RESOURCE_TYPE_MULTIPLE, SOL_LWM2M_RESOURCE_TYPE_UNKNOWN = -1 }
Enum data represents if an sol_lwm2m_resource is an array or not.
enum sol_lwm2m_tlv_type { SOL_LWM2M_TLV_TYPE_OBJECT_INSTANCE = 0, SOL_LWM2M_TLV_TYPE_RESOURCE_INSTANCE = 64, SOL_LWM2M_TLV_TYPE_MULTIPLE_RESOURCES = 128, SOL_LWM2M_TLV_TYPE_RESOURCE_WITH_VALUE = 192 }
Enum that represent the TLV type.
Functions
int sol_lwm2m_add_object_instance (struct sol_lwm2m_client *client, const struct sol_lwm2m_object *obj, const void *data)
Creates an object instance.
void sol_lwm2m_client_del (struct sol_lwm2m_client *client)
Deletes a LWM2M client.
const struct
sol_network_link_addr * sol_lwm2m_client_info_get_address (const struct sol_lwm2m_client_info *client)
Gets the client address.
enum sol_lwm2m_binding_mode sol_lwm2m_client_info_get_binding_mode (const struct sol_lwm2m_client_info *client)
Gets the client binding mode.
int sol_lwm2m_client_info_get_lifetime (const struct sol_lwm2m_client_info *client, uint32_t *lifetime)
Gets the client lifetime in seconds.
const char * sol_lwm2m_client_info_get_location (const struct sol_lwm2m_client_info *client)
Gets the client location path in the LWM2M server.
const char * sol_lwm2m_client_info_get_name (const struct sol_lwm2m_client_info *client)
Gets the name of client.
const struct sol_ptr_vector * sol_lwm2m_client_info_get_objects (const struct sol_lwm2m_client_info *client)
Get client objects.
const char * sol_lwm2m_client_info_get_objects_path (const struct sol_lwm2m_client_info *client)
Gets the client objects path.
const char * sol_lwm2m_client_info_get_sms (const struct sol_lwm2m_client_info *client)
Gets the client SMS number.
struct sol_lwm2m_client * sol_lwm2m_client_new (const char *name, const char *path, const char *sms, const struct sol_lwm2m_object **objects, const void *data)
Creates a new LWM2M client.
int sol_lwm2m_client_object_get_id (const struct sol_lwm2m_client_object *object, uint16_t *id)
Gets the object id.
const struct sol_ptr_vector * sol_lwm2m_client_object_get_instances (const struct sol_lwm2m_client_object *object)
Gets the instances of a given object.
int sol_lwm2m_client_start (struct sol_lwm2m_client *client)
Starts the LWM2M client.
int sol_lwm2m_client_stop (struct sol_lwm2m_client *client)
Stops the LWM2M client.
int sol_lwm2m_notify_observers (struct sol_lwm2m_client *client, const char **paths)
Notifies all the observing LWM2M servers that a resource has changed.
int sol_lwm2m_parse_tlv (const struct sol_str_slice content, struct sol_vector *tlv_values)
Parses a binary content into TLV.
void sol_lwm2m_resource_clear (struct sol_lwm2m_resource *resource)
Clears a sol_lwm2m_resource.
int sol_lwm2m_resource_init (struct sol_lwm2m_resource *resource, uint16_t id, uint16_t resource_len, enum sol_lwm2m_resource_data_type data_type,...)
Initializes an LWM2M resource.
int sol_lwm2m_send_update (struct sol_lwm2m_client *client)
Sends an update message to the LWM2M servers.
int sol_lwm2m_server_add_observer (struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *client, const char *path, sol_lwm2m_server_content_cb cb, const void *data)
Observers an client object, instance or resource.
int sol_lwm2m_server_add_registration_monitor (struct sol_lwm2m_server *server, sol_lwm2m_server_registration_event_cb cb, const void *data)
Adds a registration monitor.
void sol_lwm2m_server_del (struct sol_lwm2m_server *server)
Deletes a server instance.
int sol_lwm2m_server_del_observer (struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *client, const char *path, sol_lwm2m_server_content_cb cb, const void *data)
Unobserve a client object, instance or resource.
int sol_lwm2m_server_del_registration_monitor (struct sol_lwm2m_server *server, sol_lwm2m_server_registration_event_cb cb, const void *data)
Removes a registration monitor.
const struct sol_ptr_vector * sol_lwm2m_server_get_clients (const struct sol_lwm2m_server *server)
Gets all registerd clients.
int sol_lwm2m_server_management_create (struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *client, const char *path, struct sol_lwm2m_resource *resources, size_t len, sol_lwm2m_server_management_status_response_cb cb, const void *data)
Creates an object instance on a client.
int sol_lwm2m_server_management_delete (struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *client, const char *path, sol_lwm2m_server_management_status_response_cb cb, const void *data)
Deletes an object instance on a client.
int sol_lwm2m_server_management_execute (struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *client, const char *path, const char *args, sol_lwm2m_server_management_status_response_cb cb, const void *data)
Executes an resource on a client.
int sol_lwm2m_server_management_read (struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *client, const char *path, sol_lwm2m_server_content_cb cb, const void *data)
Reads an object, instance or object from a client.
int sol_lwm2m_server_management_write (struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *client, const char *path, struct sol_lwm2m_resource *resources, size_t len, sol_lwm2m_server_management_status_response_cb cb, const void *data)
Writes an object instance or resource.
struct sol_lwm2m_server * sol_lwm2m_server_new (uint16_t port)
Creates a new LWM2M server.
void sol_lwm2m_tlv_array_clear (struct sol_vector *tlvs)
Clears an TLV array.
void sol_lwm2m_tlv_clear (struct sol_lwm2m_tlv *tlv)
Clear a TLV.
int sol_lwm2m_tlv_get_bytes (struct sol_lwm2m_tlv *tlv, uint8_t **bytes, uint16_t *len)
Get TLV content is plain bytes.
int sol_lwm2m_tlv_to_bool (struct sol_lwm2m_tlv *tlv, bool *value)
Converts an TLV value to boolean value.
int sol_lwm2m_tlv_to_float (struct sol_lwm2m_tlv *tlv, double *value)
Converts an TLV value to float value.
int sol_lwm2m_tlv_to_int (struct sol_lwm2m_tlv *tlv, int64_t *value)
Converts an TLV value to int value.
int sol_lwm2m_tlv_to_obj_link (struct sol_lwm2m_tlv *tlv, uint16_t *object_id, uint16_t *instance_id)
Converts an TLV value to object link.
Detailed Description
Routines that handle LWM2M protocol.
Supported features:
Registration interface.
Management interface.
Observation interface.
TLV format.
Unsupported features for now:
Bootstrap.
LWM2M JSON.
Queue Mode operation (only 'U' is supported for now).
Data encryption.
Access rights.
Macro Definition Documentation
#define SOL_LWM2M_DEFAULT_SERVER_PORT (5683)
Macro that defines the default port for a LWM2M server.
Referenced by main().
#define SOL_LWM2M_RESOURCE_INIT (ret_value_, resource_, id_, resource_len_, data_type_, ...)
Value:
do { \
        SOL_SET_API_VERSION((resource_)->api_version = SOL_LWM2M_RESOURCE_API_VERSION; ) \
        (ret_value_) = sol_lwm2m_resource_init((resource_), (id_), (resource_len_), (data_type_), __VA_ARGS__); \
    } while (0)
Convinent macro to initialize a LWM2M resource.
This macro will first the set LWM2M resource api version then call sol_lwm2m_resource_init().
Parameters
ret_value_ The return value of sol_lwm2m_resource_init()
resource_ The resource to be initialized.
id_ The resource id.
data_type_ The resource type.
resource_len_ The resource data size.
... The LWM2M resource data, respecting the table according to the resource type.
See Also
sol_lwm2m_resource_init()
Referenced by create_location_obj(), read_location_obj(), read_security_server_obj(), and read_server_obj().
Typedef Documentation
typedef void(* sol_lwm2m_server_content_cb)(void *data, struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *client, const char *path, sol_coap_responsecode_t response_code, enum sol_lwm2m_content_type content_type, struct sol_str_slice content)
Callback used to inform a observable/read response.
Parameters
server The LWM2M server
client The LWM2M client
path The client's path
response_code The reponse code.
content_type The reponse content type.
content The reponse content.
data User data.
See Also
sol_lwm2m_server_add_observer()
sol_lwm2m_server_management_read()
sol_lwm2m_parse_tlv()
typedef void(* sol_lwm2m_server_management_status_response_cb)(void *data, struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *client, const char *path, sol_coap_responsecode_t response_code)
Callback used to inform create/write/execute/delete response.
Parameters
server The LW2M server
client The LWM2M client
path The client's path
response_code The operation response_code
data User data.
See Also
sol_lwl2m_server_management_write()
sol_lwl2m_server_management_execute()
sol_lwl2m_server_management_create()
sol_lwl2m_server_management_delete()
typedef void(* sol_lwm2m_server_registration_event_cb)(void *data, struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *cinfo, enum sol_lwm2m_registration_event event)
Callback that is used to inform a LWM2M client registration event.
Parameters
server The LWM2M server.
cinfo The client that generated the registration event.
event The registration event itself.
data User data.
See Also
sol_lwm2m_registration_event
sol_lwm2m_server_add_registration_monitor()
Enumeration Type Documentation
enum sol_lwm2m_binding_mode
LWM2M Client binding mode.
A LWM2M server, may support multiple forms of binding. The binding mode is requested by a client during its registration.
In Queue binding mode a client flags to the server that it may not be available for communication all the time, thus the server must wait until it receives a heartbeat from the client until it can send requests. The queue binding mode is usefull, because the client may enter in deep sleep and save battery and only wake up in certain times.
Note
The default binding mode is SOL_LWM2M_BINDING_MODE_U and is the only one supported right know.
See Also
sol_lwm2m_client_info_get_binding_mode()
Enumerator
SOL_LWM2M_BINDING_MODE_U
Indicates that the client is reacheable all the time and all the communication must be done using UDP.
SOL_LWM2M_BINDING_MODE_UQ
Indicate that the client is using Queued UDP binding and all the communication must be done using UDP.
SOL_LWM2M_BINDING_MODE_S
Indicates that the client is reacheable all the time and all the communication must be done using SMS.
SOL_LWM2M_BINDING_MODE_SQ
Indicates that the client is using Queued SMS binding and all the communication must be done using SMS.
SOL_LWM2M_BINDING_MODE_US
Indicates that the client is using UDP and SMS binding.
When the server sends an UDP request the client must send the response using UDP. When the server sends a SMS request the client must send the response using SMS.
SOL_LWM2M_BINDING_MODE_UQS
Indicates that the client using Queued SMS and UDP binding.
When the server sends an UDP request the client must send the response using UDP. When the server sends a SMS request the client must send the response using SMS.
SOL_LWM2M_BINDING_MODE_UNKNOWN
It was not possible to determine the client binding.
enum sol_lwm2m_content_type
Enum that represent a LWM2M response/request content type.
Enumerator
SOL_LWM2M_CONTENT_TYPE_TEXT
The content type message is pure text.
SOL_LWM2M_CONTENT_TYPE_OPAQUE
The content type of the message is undeterminated, in order words, is an array of bytes.
SOL_LWM2M_CONTENT_TYPE_TLV
The content type of the message is in TLV format.
SOL_LWM2M_CONTENT_TYPE_JSON
The content type of the message is in JSON.
JSON content types are not supported right now.
enum sol_lwm2m_registration_event
Enum that express a LWM2M client lifecycle changes.
See Also
sol_lwm2m_server_add_registration_monitor()
Enumerator
SOL_LWM2M_REGISTRATION_EVENT_REGISTER
Indicates that a client was registered in the server.
SOL_LWM2M_REGISTRATION_EVENT_UPDATE
Indicates that a client updated itself in the server.
SOL_LWM2M_REGISTRATION_EVENT_UNREGISTER
Indicates that a client was unregistered.
SOL_LWM2M_REGISTRATION_EVENT_TIMEOUT
Indicates that the server is discarting a client, since the server did not hear from it after some time.
enum sol_lwm2m_resource_data_type
Enum that represents an LWM2M resource data type.
See Also
sol_lwm2m_resource
Enumerator
SOL_LWM2M_RESOURCE_DATA_TYPE_STRING
The resource value is a string.
SOL_LWM2M_RESOURCE_DATA_TYPE_INT
The resource value is an integer.
SOL_LWM2M_RESOURCE_DATA_TYPE_FLOAT
The resource value is a float.
SOL_LWM2M_RESOURCE_DATA_TYPE_BOOLEAN
The resource value is a boolean.
SOL_LWM2M_RESOURCE_DATA_TYPE_OPAQUE
The resource value is opaque.
SOL_LWM2M_RESOURCE_DATA_TYPE_TIME
The resource value is a timestamp (Unix time).
SOL_LWM2M_RESOURCE_DATA_TYPE_OBJ_LINK
The resource value is a object link.
SOL_LWM2M_RESOURCE_DATA_TYPE_NONE
The resource value is undeterminated.
enum sol_lwm2m_resource_type
Enum data represents if an sol_lwm2m_resource is an array or not.
Enumerator
SOL_LWM2M_RESOURCE_TYPE_SINGLE
The resource type has single value.
SOL_LWM2M_RESOURCE_TYPE_MULTIPLE
The resource type is an array.
SOL_LWM2M_RESOURCE_TYPE_UNKNOWN
The resource type is unknown.
enum sol_lwm2m_tlv_type
Enum that represent the TLV type.
See Also
sol_lwm2m_tlv
Enumerator
SOL_LWM2M_TLV_TYPE_OBJECT_INSTANCE
The TLV represents an object instance.
SOL_LWM2M_TLV_TYPE_RESOURCE_INSTANCE
The TLV repreents an resource instance.
SOL_LWM2M_TLV_TYPE_MULTIPLE_RESOURCES
The TLV is composed of multiple resources.
SOL_LWM2M_TLV_TYPE_RESOURCE_WITH_VALUE
The TLV is a resource.
Function Documentation
int sol_lwm2m_add_object_instance (struct sol_lwm2m_client * client, const struct sol_lwm2m_object * obj, const void * data)
Creates an object instance.
Parameters
client The client to create the object instance..
obj The object that the instance should be created.
data The instance data.
Returns
0 on success, -errno on error.
Referenced by main().
void sol_lwm2m_client_del (struct sol_lwm2m_client * client)
Deletes a LWM2M client.
This will automatically stop the LWM2M client as well.
Parameters
client The client to be deleted.
See Also
sol_lwm2m_client_start()
Referenced by main().
const struct sol_network_link_addr* sol_lwm2m_client_info_get_address (const struct sol_lwm2m_client_info * client)
Gets the client address.
Parameters
client The LWM2M client info.
Returns
The client address or NULL on error.
enum sol_lwm2m_binding_mode sol_lwm2m_client_info_get_binding_mode (const struct sol_lwm2m_client_info * client)
Gets the client binding mode.
Parameters
client The LWM2M client info.
Returns
The client binding mode or SOL_LWM2M_BINDING_MODE_UNKNOWN on error.
int sol_lwm2m_client_info_get_lifetime (const struct sol_lwm2m_client_info * client, uint32_t * lifetime)
Gets the client lifetime in seconds.
Parameters
client The LWM2M client info.
lifetime The client lifetime to be set.
Returns
0 on success, -errno on error.
const char* sol_lwm2m_client_info_get_location (const struct sol_lwm2m_client_info * client)
Gets the client location path in the LWM2M server.
This value is specified by the LWM2M server and it will be used by the client to identify itself.
Parameters
client The LWM2M client info.
Returns
The client location path or NULL on error.
const char* sol_lwm2m_client_info_get_name (const struct sol_lwm2m_client_info * client)
Gets the name of client.
Parameters
client The LWM2M cliento info.
Returns
The client name or NULL on error.
Referenced by create_cb(), location_changed_cb(), and registration_cb().
const struct sol_ptr_vector* sol_lwm2m_client_info_get_objects (const struct sol_lwm2m_client_info * client)
Get client objects.
Parameters
client The LWM2M client info.
Returns
A array of sol_lwm2m_client_object or NULL on error.
Note
One must not add or remove elements from the returned vector.
Be adviced that it's not recommended to store object pointers, because during the client's update method, all the objects are renewed.
See Also
sol_lwm2m_client_object
Referenced by get_location_object_status().
const char* sol_lwm2m_client_info_get_objects_path (const struct sol_lwm2m_client_info * client)
Gets the client objects path.
A LWM2M client may specify an alternate objects path.
Parameters
client The LWM2M client info.
Returns
The objects path or NULL.
Note
The objects path may be NULL.
const char* sol_lwm2m_client_info_get_sms (const struct sol_lwm2m_client_info * client)
Gets the client SMS number.
A client may specify an SMS number to be used for communication.
Parameters
client The LWM2M client info.
Returns
The SMS number or NULL.
struct sol_lwm2m_client* sol_lwm2m_client_new (const char * name, const char * path, const char * sms, const struct sol_lwm2m_object ** objects, const void * data)
Creates a new LWM2M client.
This function will create a new LWM2M client with its objects. In order to start the LWM2M client and connect with the LWM2M servers, one must call sol_lwm2m_client_start.
Parameters
name The LWM2M client name, must not be NULL.
path The Objectes path, may be NUL.
sms The SMS number, may be NULL.
objects The implemented objects, must not be NULL and must be NULL terminated.
data The users data that will be passed to the object callbacks. (create, execute, read, write and del).
Returns
A LWM2M client handle or NULL on error
See Also
sol_lwm2m_client_del()
sol_lwm2m_add_object_instance()
sol_lwm2m_client_start()
Referenced by main().
int sol_lwm2m_client_object_get_id (const struct sol_lwm2m_client_object * object, uint16_t * id)
Gets the object id.
Parameters
object The LWM2M object to get the id.
id The object id to be filled.
Returns
0 success, negative errno on error.
Referenced by get_location_object_status().
const struct sol_ptr_vector* sol_lwm2m_client_object_get_instances (const struct sol_lwm2m_client_object * object)
Gets the instances of a given object.
Parameters
object The LWM2M object object to get the instances.
Returns
An array of uint16_t or NULL on error.
Note
Be adviced that it's not recommended to store object instances pointers, because they might be deleted by other LWM2M servers, thus removed from the returned list.
Referenced by get_location_object_status().
int sol_lwm2m_client_start (struct sol_lwm2m_client * client)
Starts the LWM2M client.
The LWM2M client will attempt to connect with all the registered LWM2M servers. The LWM2M client will look for the Security and Server LWM2M objects in order to connect with the LWM2M servers.
Parameters
client The client to be started.
Returns
0 on success, -errno on error.
See Also
sol_lwm2m_client_stop()
Referenced by main().
int sol_lwm2m_client_stop (struct sol_lwm2m_client * client)
Stops the LWM2M client.
This will make the LWM2M client to stop receiving/sending messages from/to the LWM2M servers. It's important to note that the objects and object instances will not be deleted.
In order to be able to respond to commands from a LWM2M server, one must call sol_lwm2m_client_start
Parameters
client The client to be stopped.
Returns
0 on success, -errno on error.
See Also
sol_lwm2m_client_start()
Referenced by main().
int sol_lwm2m_notify_observers (struct sol_lwm2m_client * client, const char ** paths)
Notifies all the observing LWM2M servers that a resource has changed.
Use this function to notify the LWM2M servers that an Object instance resource value has changed.
Parameters
client The LWM2M client.
paths The resource paths that were changed, must be NULL terminated.
Returns
0 on success, -errno on error.
Note
If a LWM2M server creates an object instance, write on a object instance or write in a object resource, the LWM2M client infrastruct will automatically notify all observing servers.
Referenced by change_location().
int sol_lwm2m_parse_tlv (const struct sol_str_slice content, struct sol_vector * tlv_values)
Parses a binary content into TLV.
Parameters
content A binary data that contains the TLV.
tlv_values An array of sol_lwm2m_tlv that will be filled.
Returns
0 on success, -errno on error.
Referenced by create_location_obj(), and location_changed_cb().
void sol_lwm2m_resource_clear (struct sol_lwm2m_resource * resource)
Clears a sol_lwm2m_resource.
Parameters
resource The resource to ne cleared.
See Also
sol_lwm2m_resource_init()
Referenced by create_location_obj().
int sol_lwm2m_resource_init (struct sol_lwm2m_resource * resource, uint16_t id, uint16_t resource_len, enum sol_lwm2m_resource_data_type data_type, ...)
Initializes an LWM2M resource.
This function makes it easier to init a LWM2M resource, it will set the proper fields and fill its data. Note that the last argument type varies with the resource type and one must follow the table below.
Resource type Last argument type
SOL_LWM2M_RESOURCE_DATA_TYPE_STRING struct sol_str_slice
SOL_LWM2M_RESOURCE_DATA_TYPE_INT int64_t
SOL_LWM2M_RESOURCE_DATA_TYPE_FLOAT double
SOL_LWM2M_RESOURCE_DATA_TYPE_BOOLEAN bool
SOL_LWM2M_RESOURCE_DATA_TYPE_OPAQUE struct sol_str_slice
SOL_LWM2M_RESOURCE_DATA_TYPE_TIME int64_t
SOL_LWM2M_RESOURCE_DATA_TYPE_OBJ_LINK uint16_t, uint16_t
Parameters
resource The resource to be initialized.
id The resource id.
data_type The resource type.
resource_len The resource data size.
... The LWM2M resource data, respecting the table according to the resource type.
Returns
0 on success, negative errno on error.
See Also
sol_lwm2m_resource_clear()
SOL_LWM2M_RESOURCE_INIT()
Note
The LWM2M resource api_version must be set, before calling this function.
int sol_lwm2m_send_update (struct sol_lwm2m_client * client)
Sends an update message to the LWM2M servers.
This will trigger the update method of the LWM2M registration interface. The client will send an update to all the registered LWM2M servers.
Parameters
client The client to send the update request.
Returns
0 on success, -errno on error.
Referenced by execute_server_obj().
int sol_lwm2m_server_add_observer (struct sol_lwm2m_server * server, struct sol_lwm2m_client_info * client, const char * path, sol_lwm2m_server_content_cb cb, const void * data)
Observers an client object, instance or resource.
Every time the observed path changes, the client will notify the LWM2M server.
Parameters
server The LWM2M server.
client The LWM2M client to be observed.
path The path to be observed (Example: /3/0/0).
cb A callback to eb called when the observed path changes.
data User data to cb
Returns
0 on success, -errno on error.
See Also
sol_lwm2m_server_content_cb
sol_lwm2m_server_del_observer()
Referenced by observe_location().
int sol_lwm2m_server_add_registration_monitor (struct sol_lwm2m_server * server, sol_lwm2m_server_registration_event_cb cb, const void * data)
Adds a registration monitor.
This function register a monitor, making it easir to observe a LWM2M client's life cycle. This means that everytime a LWM2M client is registered, updated, deleted or timedout, cb will be called.
Parameters
server The LWM2M server.
cb The previous registered callback.
data The user data to cb.
Returns
0 on success, -errno on error.
See Also
sol_lwm2m_server_add_registration_monitor()
sol_lwm2m_server_registration_event_cb
Referenced by main().
void sol_lwm2m_server_del (struct sol_lwm2m_server * server)
Deletes a server instance.
Use this function to stop the LWM2M server and release its resources.
Parameters
server The LWM2M server to be deleted.
See Also
sol_lwm2m_server_del()
Referenced by main().
int sol_lwm2m_server_del_observer (struct sol_lwm2m_server * server, struct sol_lwm2m_client_info * client, const char * path, sol_lwm2m_server_content_cb cb, const void * data)
Unobserve a client object, instance or resource.
Parameters
server The LWM2M server.
client The LWM2M client to be unobserved.
path The path to be unobserved (Example: /3/0/0).
cb The previous registered callback.
data User data to cb
Returns
0 on success, -errno on error.
Note
In order do completly unobserve a path, all observers must be deleted.
See Also
sol_lwm2m_server_content_cb
sol_lwm2m_server_add_observer()
int sol_lwm2m_server_del_registration_monitor (struct sol_lwm2m_server * server, sol_lwm2m_server_registration_event_cb cb, const void * data)
Removes a registration monitor.
Parameters
server The LWM2M server.
cb The previous registered callback.
data The user data to cb.
Returns
0 on success, -errno on error.
See Also
sol_lwm2m_server_add_registration_monitor()
const struct sol_ptr_vector* sol_lwm2m_server_get_clients (const struct sol_lwm2m_server * server)
Gets all registerd clients.
Parameters
server The LWM2M Server.
Returns
An vector of sol_lwm2m_client_info or NULL on error.
Note
One must not add or remove elements from the returned vector.
See Also
sol_lwm2m_server_add_registration_monitor()
int sol_lwm2m_server_management_create (struct sol_lwm2m_server * server, struct sol_lwm2m_client_info * client, const char * path, struct sol_lwm2m_resource * resources, size_t len, sol_lwm2m_server_management_status_response_cb cb, const void * data)
Creates an object instance on a client.
Parameters
server The LWM2M server.
client The LWM2M client info to create an object instance.
path The object path to create be created (Example /1).
resources An array of sol_lwm2m_resource which contains the required resources to create an object.
len The length of resources.
cb A callback to be called when the create operation is completed.
data User data to cb
Returns
0 on success, -errno on error.
Note
All data is sent using TLV.
See Also
sol_lwm2m_server_management_status_response_cb
Referenced by create_location_obj().
int sol_lwm2m_server_management_delete (struct sol_lwm2m_server * server, struct sol_lwm2m_client_info * client, const char * path, sol_lwm2m_server_management_status_response_cb cb, const void * data)
Deletes an object instance on a client.
Parameters
server The LWM2M server.
client The LWM2M client info to delete an object
path The object path to be deleted (Example /1/1).
cb A callback to be called when the delete operation is completed.
data User data to cb
Returns
0 on success, -errno on error.
See Also
sol_lwm2m_server_management_status_response_cb
int sol_lwm2m_server_management_execute (struct sol_lwm2m_server * server, struct sol_lwm2m_client_info * client, const char * path, const char * args, sol_lwm2m_server_management_status_response_cb cb, const void * data)
Executes an resource on a client.
Parameters
server The LWM2M server.
client The LWM2M client info to execute the resource.
path The object path to be executed (Example /1/1/8).
args Arguments to the execute command.
cb A callback to be called when the execute operation is completed.
data User data to cb
Returns
0 on success, -errno on error.
See Also
sol_lwm2m_server_management_status_response_cb
int sol_lwm2m_server_management_read (struct sol_lwm2m_server * server, struct sol_lwm2m_client_info * client, const char * path, sol_lwm2m_server_content_cb cb, const void * data)
Reads an object, instance or object from a client.
Parameters
server The LWM2M server.
client The LWM2M client info to be read.
path The path to be read (Example /3/0/0).
cb A callback to be called when the read operation is completed.
data User data to cb
Returns
0 on success, -errno on error.
See Also
sol_lwm2m_server_content_cb
int sol_lwm2m_server_management_write (struct sol_lwm2m_server * server, struct sol_lwm2m_client_info * client, const char * path, struct sol_lwm2m_resource * resources, size_t len, sol_lwm2m_server_management_status_response_cb cb, const void * data)
Writes an object instance or resource.
Parameters
server The LWM2M server.
client The LWM2M client info to write
path The object path to be written (Example /1/1).
resources An array of sol_lwm2m_resource
len The length of resources
cb A callback to be called when the write operation is completed.
data User data to cb
Returns
0 on success, -errno on error.
Note
All data is sent using TLV.
See Also
sol_lwm2m_server_management_status_response_cb
struct sol_lwm2m_server* sol_lwm2m_server_new (uint16_t port)
Creates a new LWM2M server.
The server will be immediately operational and waiting for connections.
Parameters
port The UDP port to be used.
Returns
The LWM2M server or NULL on error.
Referenced by main().
void sol_lwm2m_tlv_array_clear (struct sol_vector * tlvs)
Clears an TLV array.
Parameters
tlvs The TLVs array to be cleared.
Referenced by create_location_obj(), and location_changed_cb().
void sol_lwm2m_tlv_clear (struct sol_lwm2m_tlv * tlv)
Clear a TLV.
Parameters
tlv The TLV the be cleared.
int sol_lwm2m_tlv_get_bytes (struct sol_lwm2m_tlv * tlv, uint8_t ** bytes, uint16_t * len)
Get TLV content is plain bytes.
Parameters
tlv The tlv data.
bytes The content.
len The length of bytes
Returns
0 on succes, -errno on error.
Referenced by create_location_obj(), and location_changed_cb().
int sol_lwm2m_tlv_to_bool (struct sol_lwm2m_tlv * tlv, bool * value)
Converts an TLV value to boolean value.
Parameters
tlv The tlv data.
value The converted value.
Returns
0 on success, -errno on error.
int sol_lwm2m_tlv_to_float (struct sol_lwm2m_tlv * tlv, double * value)
Converts an TLV value to float value.
Parameters
tlv The tlv data.
value The converted value.
Returns
0 on success, -errno on error.
int sol_lwm2m_tlv_to_int (struct sol_lwm2m_tlv * tlv, int64_t * value)
Converts an TLV value to int value.
Parameters
tlv The tlv data.
value The converted value.
Returns
0 on success, -errno on error.
Referenced by create_location_obj().
int sol_lwm2m_tlv_to_obj_link (struct sol_lwm2m_tlv * tlv, uint16_t * object_id, uint16_t * instance_id)
Converts an TLV value to object link.
Parameters
tlv The tlv data.
object_id The object id.
instance_id the instance id.
Returns
0 on success, -errno on error.