Soletta: OIC Client
OIC Client
Open Interconnect Consortium
Routines to create clients talking OIC protocol.
Data Structures
struct sol_oic_resource
Structure defining an oic resource.
Functions
void sol_oic_client_del (struct sol_oic_client *client)
Delete client.
bool sol_oic_client_find_resource (struct sol_oic_client *client, struct sol_network_link_addr *addr, const char *resource_type, bool(*resource_found_cb)(struct sol_oic_client *cli, struct sol_oic_resource *res, void *data), const void *data)
Send a discovevery packet to find resources.
bool sol_oic_client_get_platform_info (struct sol_oic_client *client, struct sol_oic_resource *resource, void(*info_received_cb)(struct sol_oic_client *cli, const struct sol_oic_platform_information *info, void *data), const void *data)
Retrieve platform information.
bool sol_oic_client_get_platform_info_by_addr (struct sol_oic_client *client, struct sol_network_link_addr *addr, void(*info_received_cb)(struct sol_oic_client *cli, const struct sol_oic_platform_information *info, void *data), const void *data)
Retrieve platform information from addr.
bool sol_oic_client_get_server_info (struct sol_oic_client *client, struct sol_oic_resource *resource, void(*info_received_cb)(struct sol_oic_client *cli, const struct sol_oic_server_information *info, void *data), const void *data)
Retrieve server information.
bool sol_oic_client_get_server_info_by_addr (struct sol_oic_client *client, struct sol_network_link_addr *addr, void(*info_received_cb)(struct sol_oic_client *cli, const struct sol_oic_server_information *info, void *data), const void *data)
Retrieve server information from addr.
struct sol_oic_client * sol_oic_client_new (void)
Creates a new OIC client intance.
bool sol_oic_client_resource_non_confirmable_request (struct sol_oic_client *client, struct sol_oic_resource *res, sol_coap_method_t method, bool(*fill_repr_map)(void *data, struct sol_oic_map_writer *repr_map), void *fill_repr_map_data, void(*callback)(sol_coap_responsecode_t response_code, struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_oic_map_reader *repr_vec, void *data), const void *callback_data)
Send a request packet to server for specific resource, using non-confirmable packets.
bool sol_oic_client_resource_request (struct sol_oic_client *client, struct sol_oic_resource *res, sol_coap_method_t method, bool(*fill_repr_map)(void *data, struct sol_oic_map_writer *repr_map), void *fill_repr_map_data, void(*callback)(sol_coap_responsecode_t response_code, struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_oic_map_reader *repr_vec, void *data), const void *callback_data)
Send a request packet to server for specific resource.
bool sol_oic_client_resource_set_observable (struct sol_oic_client *client, struct sol_oic_resource *res, void(*callback)(sol_coap_responsecode_t response_code, struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_oic_map_reader *repr_map, void *data), const void *data, bool observe)
Set this resource as observable for this client.
bool sol_oic_client_resource_set_observable_non_confirmable (struct sol_oic_client *client, struct sol_oic_resource *res, void(*callback)(sol_coap_responsecode_t response_code, struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_oic_map_reader *repr_map, void *data), const void *data, bool observe)
Set this resource as observable for this client, using non-confirmable packets.
struct sol_oic_resource * sol_oic_resource_ref (struct sol_oic_resource *r)
Take a reference of the given server.
void sol_oic_resource_unref (struct sol_oic_resource *r)
Release a reference from the given resource.
Detailed Description
Routines to create clients talking OIC protocol.
Function Documentation
void sol_oic_client_del (struct sol_oic_client * client)
Delete client.
All memory used by client and all resources associated with it will be freed.
Parameters
client The client to delete.
See Also
sol_oic_client_new()
Referenced by main().
bool sol_oic_client_find_resource (struct sol_oic_client * client, struct sol_network_link_addr * addr, const char * resource_type, bool(*)(struct sol_oic_client *cli, struct sol_oic_resource *res, void *data) resource_found_cb, const void * data)
Send a discovevery packet to find resources.
Sends a discovery packet to the destination address especified by addr, which may be a multicast address for discovery purposes.
When a response is received, the function resource_found_cb will be called. Note that multiple responses can be received for this request. As long as this function returns true, client will continue waiting for more responses. When the function returns false, the internal response handler will be freed and any new replies that arrive for this request will be ignored. After internal timeout is reached resource_found_cb will be called with NULL oic_res. The same behavior is expected for resource_found_cb return, if resource_found_cb returns true, client will continue waiting responses until next timeout. If resource_found_cb returns false, client will terminate response waiting.
Parameters
client An oic client instance.
addr The address of the server that contains the desired resource. May be a multicast address if it is desired to look for resources in multiple servers.
resource_type A string representation of the type of the desired resource.
resource_found_cb Callback to be called when a resource is found or when timeout is reached. Parameter cli is the sol_oic_client used to perform the request, res is the resource that was discovered and data is a pointer to the user's data parameter.
data A pointer to user's data.
Returns
True if packet was successfully sent. False otherwise.
Referenced by main().
bool sol_oic_client_get_platform_info (struct sol_oic_client * client, struct sol_oic_resource * resource, void(*)(struct sol_oic_client *cli, const struct sol_oic_platform_information *info, void *data) info_received_cb, const void * data)
Retrieve platform information.
Sends a packet to resource's server asking for platform information defined at sol_oic_platform_information.
When a response is received, the function info_received_cb will be called, with info parameter filled with the information received, or NULL on errors. As info_received_cb is always called, it can be used to perform clean up operations.
After internal timeout is reached info_received_cb will be called with NULL info and any clean up can be performed.
Parameters
client An oic client instance.
resource The resource that is going to receive the request.
info_received_cb Callback to be called when response is received or when timeout is reached. Parameter cli is the sol_oic_client used to perform the request, info is the sol_oic_platform_information structure with server info data, data is a pointer to user's data parameter.
data A pointer to user's data.
Returns
True if packet was successfully sent. False otherwise.
bool sol_oic_client_get_platform_info_by_addr (struct sol_oic_client * client, struct sol_network_link_addr * addr, void(*)(struct sol_oic_client *cli, const struct sol_oic_platform_information *info, void *data) info_received_cb, const void * data)
Retrieve platform information from addr.
Sends a packet to server identified by addr asking for platform information defined at sol_oic_platform_information.
When a response is received, the function info_received_cb will be called, with info parameter filled with the information received, or NULL on errors. As info_received_cb is always called, it can be used to perform clean up operations.
After internal timeout is reached info_received_cb will be called with NULL info and any clean up can be performed.
Parameters
client An oic client instance.
addr The address of the server that contains the desired information.
info_received_cb Callback to be called when response is received or when timeout is reached. Parameter cli is the sol_oic_client used to perform the request, info is the sol_oic_platform_information structure with server info data, data is a pointer to user's data parameter.
data A pointer to user's data.
Returns
True if packet was successfully sent. False otherwise.
Referenced by main().
bool sol_oic_client_get_server_info (struct sol_oic_client * client, struct sol_oic_resource * resource, void(*)(struct sol_oic_client *cli, const struct sol_oic_server_information *info, void *data) info_received_cb, const void * data)
Retrieve server information.
Sends a packet to resource's server asking for server information defined at sol_oic_server_information.
When a response is received, the function info_received_cb will be called, with info parameter filled with the information received, or NULL on errors. As info_received_cb is always called, it can be used to perform clean up operations.
After internal timeout is reached info_received_cb will be called with NULL info and any clean up can be performed.
Parameters
client An oic client instance.
resource The resource that is going to receive the request.
info_received_cb Callback to be called when response is received or when timeout is reached. Parameter cli is the sol_oic_client used to perform the request, info is the sol_oic_server_information structure with server info data, data is a pointer to user's data parameter.
data A pointer to user's data.
Returns
True if packet was successfully sent. False otherwise.
bool sol_oic_client_get_server_info_by_addr (struct sol_oic_client * client, struct sol_network_link_addr * addr, void(*)(struct sol_oic_client *cli, const struct sol_oic_server_information *info, void *data) info_received_cb, const void * data)
Retrieve server information from addr.
Sends a packet to server identified by addr asking for server information defined at sol_oic_server_information.
When a response is received, the function info_received_cb will be called, with info parameter filled with the information received, or NULL on errors. As info_received_cb is always called, it can be used to perform clean up operations.
After internal timeout is reached info_received_cb will be called with NULL info and any clean up can be performed.
Parameters
client An oic client instance.
addr The address of the server that contains the desired information.
info_received_cb Callback to be called when response is received or when timeout is reached. Parameter cli is the sol_oic_client used to perform the request, info is the sol_oic_server_information structure with server info data, data is a pointer to user's data parameter.
data A pointer to user's data.
Returns
True if packet was successfully sent. False otherwise.
Referenced by main().
struct sol_oic_client* sol_oic_client_new (void)
Creates a new OIC client intance.
Returns
A new OIC client instance, or NULL in case of failure.
See Also
sol_oic_client_del()
Referenced by main().
bool sol_oic_client_resource_non_confirmable_request (struct sol_oic_client * client, struct sol_oic_resource * res, sol_coap_method_t method, bool(*)(void *data, struct sol_oic_map_writer *repr_map) fill_repr_map, void * fill_repr_map_data, void(*)(sol_coap_responsecode_t response_code, struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_oic_map_reader *repr_vec, void *data) callback, const void * callback_data)
Send a request packet to server for specific resource, using non-confirmable packets.
Send a CoAP non-confirmable request packet to server that contains the resource and wait for a response. When the response arrives, callback will be called.
The only difference from sol_oic_client_resource_request() to this function is that it uses CoAP non-confirmable packets to make the request.
Parameters
client An oic client instance.
res The resource that is going to receive the request.
method The coap request method as documented in sol_coap_method_t.
fill_repr_map A callback to be called to fill the request data. Parameter data is a pointer to user's fill_repr_map_data and repr_map is a handler to write data to request packet. Use sol_oic_map_append() to append data to repr_map. If NULL, no data will be added to request.
fill_repr_map_data User's data to be passed to fill_repr_map.
callback Callback to be called when a response from this request arrives. Parameter response_code is the header response code of this request, cli is the client used to perform the request, addr is the address of the server and repr_vec is a handler to access data from response, using SOL_OIC_MAP_LOOP() macro. data is the user's callback_data. When timeout is reached and no packet has arrived, callback is called with NULL addr and NULL repr_vec so any clean up can be performed.
callback_data User's data to be passed to callback.
Returns
True if packet was successfully sent. False otherwise.
Referenced by found_resource().
bool sol_oic_client_resource_request (struct sol_oic_client * client, struct sol_oic_resource * res, sol_coap_method_t method, bool(*)(void *data, struct sol_oic_map_writer *repr_map) fill_repr_map, void * fill_repr_map_data, void(*)(sol_coap_responsecode_t response_code, struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_oic_map_reader *repr_vec, void *data) callback, const void * callback_data)
Send a request packet to server for specific resource.
Send a CoAP confirmable request packet to server that contains the resource and wait for a response. When the response arrives, callback will be called.
Parameters
client An oic client instance.
res The resource that is going to receive the request.
method The coap request method as documented in sol_coap_method_t.
fill_repr_map A callback to be called to fill the request data. Parameter data is a pointer to user's fill_repr_map_data and repr_map is a handler to write data to request packet. Use sol_oic_map_append() to append data to repr_map. If NULL, no data will be added to request.
fill_repr_map_data User's data to be passed to fill_repr_map.
callback Callback to be called when a response from this request arrives. Parameter response_code is the header response code of this request, cli is the client used to perform the request, addr is the address of the server and repr_vec is a handler to access data from response, using SOL_OIC_MAP_LOOP() macro. data is the user's callback_data. When timeout is reached and no packet has arrived, callback is called with NULL addr and NULL repr_vec so any clean up can be performed.
callback_data User's data to be passed to callback.
Returns
True if packet was successfully sent. False otherwise.
Referenced by found_resource(), and print_response().
bool sol_oic_client_resource_set_observable (struct sol_oic_client * client, struct sol_oic_resource * res, void(*)(sol_coap_responsecode_t response_code, struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_oic_map_reader *repr_map, void *data) callback, const void * data, bool observe)
Set this resource as observable for this client.
If server providing the resource supports observing clients, sends a request to server asking it to add client to its observing list. Clients in observation receives notifications when server status changes. When a notification is received by client, callback will be called. If the resource is not observable, client will emulate the observing behavior using a polling strategy, so callback will be notified with server changes from time to time.
When user wants to stop observing the server, call sol_oic_client_resource_set_observable() with observe as false.
Parameters
client An oic client instance.
res The resource that is going to be observed
callback A callback to be called when notification responses arrive. Parameter response_code is the header response code of this request, cli is the client used to perform the request, addr is the address of the server, repr_map is the data from the notification and data is a pointer to user's data. To extract data from repr_map use SOL_OIC_MAP_LOOP() macro. Callback is called with NULL addr and NULL repr_map when client is unobserved, so any clean up can be performed.
data A pointer to user's data.
observe If server will be obeserved or unobserved.
Returns
True if packet was successfully sent. False otherwise.
Referenced by found_resource().
bool sol_oic_client_resource_set_observable_non_confirmable (struct sol_oic_client * client, struct sol_oic_resource * res, void(*)(sol_coap_responsecode_t response_code, struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_oic_map_reader *repr_map, void *data) callback, const void * data, bool observe)
Set this resource as observable for this client, using non-confirmable packets.
If server providing the resource supports observing clients, sends a request to server asking it to add client to its observing list. Clients in observation receives notifications when server status changes. When a notification is received by client, callback will be called. If the resource is not observable, client will emulate the observing behavior using a polling strategy, so callback will be notified with server changes from time to time.
When user wants to stop observing the server, call sol_oic_client_resource_set_observable() with observe as false.
The only difference from sol_oic_client_resource_set_observable() to this function is that it uses CoAP non-confirmable packets to make the request.
Parameters
client An oic client instance.
res The resource that is going to be observed
callback A callback to be called when notification responses arrive. Parameter response_code is the header response code of this request, cli is the client used to perform the request, addr is the address of the server, repr_map is the data from the notification and data is a pointer to user's data. To extract data from repr_map use SOL_OIC_MAP_LOOP() macro. Callback is called with NULL addr and NULL repr_map when client is unobserved, so any clean up can be performed.
data A pointer to user's data.
observe If server will be obeserved or unobserved.
Returns
True if packet was successfully sent. False otherwise.
Referenced by found_resource().
struct sol_oic_resource* sol_oic_resource_ref (struct sol_oic_resource * r)
Take a reference of the given server.
Increment the reference count of the resource, if it's valid.
Parameters
r The resource to reference.
Returns
The same resource, with refcount increased, or NULL if invalid.
Referenced by found_resource().
void sol_oic_resource_unref (struct sol_oic_resource * r)
Release a reference from the given resource.
When the last reference is released, the resource with it will be freed.
Parameters
r The resource to release.
Referenced by found_resource(), and main().