Soletta: Soletta file utility functions
Soletta file utility functions
Soletta utility functions.
Contains helpers to deal with files.
Macros
#define SOL_UTIL_MAX_READ_ATTEMPTS 10
Max number of read attempts.
Functions
int sol_util_fd_set_flag (int fd, int flag) SOL_ATTR_WARN_UNUSED_RESULT
Set a flag into a file descriptor.
ssize_t sol_util_fill_buffer (const int fd, struct sol_buffer *buffer, const size_t size)
Fills buffer with data read from file fd.
static int sol_util_fill_buffer_exactly (const int fd, struct sol_buffer *buffer, const size_t size)
Fills buffer with data read from file fd with an exact amount of bytes.
int sol_util_get_rootdir (char *out, size_t size) SOL_ATTR_WARN_UNUSED_RESULT
Gets the root directory.
bool sol_util_iterate_dir (const char *path, bool(*iterate_dir_cb)(void *data, const char *dir_path, struct dirent *ent), const void *data)
Iterate over a directory.
int sol_util_load_file_buffer (const char *filename, struct sol_buffer *buf) SOL_ATTR_WARN_UNUSED_RESULT
Reads the contents of a file and append to a buffer.
int sol_util_load_file_fd_buffer (int fd, struct sol_buffer *buf) SOL_ATTR_WARN_UNUSED_RESULT
Reads the contents of a file and append to a buffer.
int int int int struct sol_buffer * sol_util_load_file_fd_raw (const int fd) SOL_ATTR_WARN_UNUSED_RESULT
Reads the contents of a file.
char * sol_util_load_file_fd_string (const int fd, size_t *size) SOL_ATTR_WARN_UNUSED_RESULT
Reads the contents of a file.
char * sol_util_load_file_string (const char *filename, size_t *size) SOL_ATTR_WARN_UNUSED_RESULT
Reads the contents of a file.
int sol_util_move_file (const char *old_path, const char *new_path, mode_t mode)
Moves file on filesystem.
int int int sol_util_read_file (const char *path, const char *fmt,...) SOL_ATTR_SCANF(2
Reads from a file the contents according with the formatted string.
int int int int sol_util_vread_file (const char *path, const char *fmt, va_list args) SOL_ATTR_SCANF(2
Reads from a file the contents according with the formatted string.
int int sol_util_vwrite_file (const char *path, const char *fmt, va_list args) SOL_ATTR_PRINTF(2
Write the formatted string in the file pointed by path.
int sol_util_write_file (const char *path, const char *fmt,...) SOL_ATTR_PRINTF(2
Write the formatted string in the file pointed by path.
Detailed Description
Contains helpers to deal with files.
Macro Definition Documentation
#define SOL_UTIL_MAX_READ_ATTEMPTS 10
Max number of read attempts.
It's used when a read operation returns EAGAIN or EINTR.
Function Documentation
int sol_util_fd_set_flag (int fd, int flag)
Set a flag into a file descriptor.
Parameters
fd A valid file descriptor.
flag The desired flag.
Returns
0 on success, otherwise a negative value with the error.
Referenced by startup_server().
ssize_t sol_util_fill_buffer (const int fd, struct sol_buffer * buffer, const size_t size)
Fills buffer with data read from file fd.
Data read will be appended to the end of used buffer (i.e. buffer->used). If one wants data to be inserted at beginning of buffer, then one must call sol_buffer_reset() on buffer before calling sol_util_fill_buffer().
By using this function to fill the buffer, one doesn't need to care about EAGAIN or EINTR being returned by read() raw call.
Parameters
fd A valid file descriptor.
buffer The buffer that will hold the file's content.
size Read up to this amount of bytes.
Returns
The size of bytes filled in success, otherwise a negative error indicating what failure happened. Note that the amount of bytes may be smaller than the requested.
See Also
sol_util_fill_buffer_exactly()
Referenced by sol_util_fill_buffer_exactly().
static int sol_util_fill_buffer_exactly (const int fd, struct sol_buffer * buffer, const size_t size) inline static
Fills buffer with data read from file fd with an exact amount of bytes.
Data read will be appended to the end of used buffer (i.e. buffer->used). If one wants data to be inserted at beginning of buffer, then one must call sol_buffer_reset() on buffer before calling sol_util_fill_buffer_exactly()
By using this function to fill the buffer, one doesn't need to care about EAGAIN or EINTR being returned by read() raw call.
This is a convenience function that calls sol_util_fill_buffer() and check if the read amount is exactly the given size, otherwise considers a failure.
Parameters
fd A valid file descriptor.
buffer The buffer that will hold the file's content.
size Read exactly this amount of bytes.
Returns
0 on success, -EIO if the number of bytes read is smaller than size or -errno on errrors.
See Also
sol_util_fill_buffer()
References sol_util_fill_buffer().
int sol_util_get_rootdir (char * out, size_t size)
Gets the root directory.
Parameters
out A variable to hold the root directory.
size The out's size
Returns
0 on success, otherwise a negative value with the error.
Referenced by show_module_types().
bool sol_util_iterate_dir (const char * path, bool(*)(void *data, const char *dir_path, struct dirent *ent) iterate_dir_cb, const void * data)
Iterate over a directory.
Parameters
path A valid path.
iterate_dir_cb The callback called in which directory found.
data The user data which will be passed in the callback.
Returns
true on success, otherwise false.
int sol_util_load_file_buffer (const char * filename, struct sol_buffer * buf)
Reads the contents of a file and append to a buffer.
Parameters
filename THe file path to be read.
buf A buffer to append the file contents - It must be initialized.
Returns
0 on success, negative errno otherwise.
int sol_util_load_file_fd_buffer (int fd, struct sol_buffer * buf)
Reads the contents of a file and append to a buffer.
Parameters
fd A valid file descriptor.
buf A buffer to append the file contents - It must be initialized.
Returns
0 on success, negative errno otherwise.
Referenced by on_stdin().
int int int int struct sol_buffer* sol_util_load_file_fd_raw (const int fd)
Reads the contents of a file.
The data read is put not formatted in a buffer.
Note
It's the caller responsibility to release the buffer's memory.
Parameters
fd A valid file descriptor.
Returns
A buffer with the data read in success, otherwise NULL.
See Also
sol_util_load_file_string
char* sol_util_load_file_fd_string (const int fd, size_t * size)
Reads the contents of a file.
Note
It's the caller responsibility to release the memory.
Parameters
fd A valid file descriptor.
size A variable to hold the amount of read data.
Returns
A string with the file's content on success, otherwise NULL.
See Also
sol_util_load_file_string
char* sol_util_load_file_string (const char * filename, size_t * size)
Reads the contents of a file.
Note
It's the caller responsibility to release the memory.
Parameters
filename A file's path.
size A variable to hold the amount of read data.
Returns
A string with the file's content on success, otherwise NULL.
See Also
sol_util_load_file_fd_string
int sol_util_move_file (const char * old_path, const char * new_path, mode_t mode)
Moves file on filesystem.
This function shall move file from old_path to new_path, and it only returns success if ensures that file was written to storage, using fsync(3)
Parameters
old_path path of file to be moved
new_path to where move file
mode mode that should be applied to new_file
Returns
On success 0. On failure, a negative error indicating what failure happened.
Note
This function may take time to complete its task, thus blocking the mainloop. You may want to use a thread or idler to call it.
int int int sol_util_read_file (const char * path, const char * fmt, ...)
Reads from a file the contents according with the formatted string.
Parameters
path The path to a valid file.
fmt The string format.
Returns
The number of read characters, if an error is encountered a negative value with the error.
See Also
sol_util_vread_file
Referenced by parse_kcmdline_pin().
int int int int sol_util_vread_file (const char * path, const char * fmt, va_list args)
Reads from a file the contents according with the formatted string.
It is equivalent to sol_util_read_file except it receives va_list instead of a variable number of arguments.
Parameters
path The path to a valid file.
fmt The string format.
args The format arguments.
Returns
The number of read characters, if an error is encountered a negative value with the error.
See Also
sol_util_vread_file
int int sol_util_vwrite_file (const char * path, const char * fmt, va_list args)
Write the formatted string in the file pointed by path.
It is equivalent to sol_util_write_file except it receives va_list instead of a variable number of arguments.
Parameters
path The path to a valid file.
fmt The string format
args The format arguments.
Returns
The number of written characters, if an error is encountered a negative value with the error.
See Also
sol_util_write_file
int sol_util_write_file (const char * path, const char * fmt, ...)
Write the formatted string in the file pointed by path.
Parameters
path The path to a valid file.
fmt The string format.
Returns
The number of written characters, if an error is encountered a negative value with the error.
See Also
sol_util_vwrite_file