Soletta: src/samples/coap/lwm2m-server.c File Reference
lwm2m-server.c File Reference
#include "sol-lwm2m.h"
#include "sol-mainloop.h"
#include "sol-vector.h"
#include "sol-util.h"
#include <stdio.h>
#include <stdbool.h>
#include <errno.h>
Macros
#define LATITUDE_ID (0)
#define LOCATION_OBJ_ID (6)
#define LONGITUDE_ID (1)
#define TIMESTAMP_ID (5)
Enumerations
enum location_object_status { LOCATION_OBJECT_NOT_FOUND, LOCATION_OBJECT_WITH_NO_INSTANCES, LOCATION_OBJECT_WITH_INSTANCES }
Functions
static void create_cb (void *data, struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *cinfo, const char *path, sol_coap_responsecode_t response_code)
static void create_location_obj (struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *cinfo)
static enum location_object_status get_location_object_status (const struct sol_lwm2m_client_info *cinfo)
static void location_changed_cb (void *data, struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *cinfo, const char *path, sol_coap_responsecode_t response_code, enum sol_lwm2m_content_type content_type, struct sol_str_slice content)
int main (int argc, char *argv[])
static void observe_location (struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *cinfo)
static void registration_cb (void *data, struct sol_lwm2m_server *server, struct sol_lwm2m_client_info *cinfo, enum sol_lwm2m_registration_event event)
Macro Definition Documentation
#define LATITUDE_ID (0)
Referenced by create_location_obj(), and location_changed_cb().
#define LOCATION_OBJ_ID (6)
Referenced by get_location_object_status().
#define LONGITUDE_ID (1)
Referenced by create_location_obj(), and location_changed_cb().
#define TIMESTAMP_ID (5)
Referenced by create_location_obj().
Enumeration Type Documentation
enum location_object_status
Enumerator
LOCATION_OBJECT_NOT_FOUND
LOCATION_OBJECT_WITH_NO_INSTANCES
LOCATION_OBJECT_WITH_INSTANCES
Function Documentation
static void create_cb (void * data, struct sol_lwm2m_server * server, struct sol_lwm2m_client_info * cinfo, const char * path, sol_coap_responsecode_t response_code) static
References observe_location(), SOL_COAP_RSPCODE_CREATED, and sol_lwm2m_client_info_get_name().
Referenced by create_location_obj().
static void create_location_obj (struct sol_lwm2m_server * server, struct sol_lwm2m_client_info * cinfo) static
References create_cb(), LATITUDE_ID, LONGITUDE_ID, sol_lwm2m_resource_clear(), SOL_LWM2M_RESOURCE_DATA_TYPE_STRING, SOL_LWM2M_RESOURCE_DATA_TYPE_TIME, SOL_LWM2M_RESOURCE_INIT, sol_lwm2m_server_management_create(), SOL_UTIL_ARRAY_SIZE, and TIMESTAMP_ID.
Referenced by registration_cb().
static enum location_object_status get_location_object_status (const struct sol_lwm2m_client_info * cinfo) static
References LOCATION_OBJ_ID, LOCATION_OBJECT_NOT_FOUND, LOCATION_OBJECT_WITH_INSTANCES, LOCATION_OBJECT_WITH_NO_INSTANCES, sol_lwm2m_client_info_get_objects(), sol_lwm2m_client_object_get_id(), sol_lwm2m_client_object_get_instances(), SOL_PTR_VECTOR_FOREACH_IDX, and sol_ptr_vector_get_len().
Referenced by registration_cb().
static void location_changed_cb (void * data, struct sol_lwm2m_server * server, struct sol_lwm2m_client_info * cinfo, const char * path, sol_coap_responsecode_t response_code, enum sol_lwm2m_content_type content_type, struct sol_str_slice content) static
References sol_lwm2m_tlv::id, LATITUDE_ID, LONGITUDE_ID, SOL_COAP_RSPCODE_CHANGED, SOL_COAP_RSPCODE_CONTENT, sol_lwm2m_client_info_get_name(), SOL_LWM2M_CONTENT_TYPE_TLV, sol_lwm2m_parse_tlv(), sol_lwm2m_tlv_array_clear(), sol_lwm2m_tlv_get_bytes(), and SOL_VECTOR_FOREACH_IDX.
Referenced by observe_location().
int main (int argc, char * argv[])
References registration_cb(), server, sol_init(), SOL_LWM2M_DEFAULT_SERVER_PORT, sol_lwm2m_server_add_registration_monitor(), sol_lwm2m_server_del(), sol_lwm2m_server_new(), sol_run(), and sol_shutdown().
static void observe_location (struct sol_lwm2m_server * server, struct sol_lwm2m_client_info * cinfo) static
References location_changed_cb(), and sol_lwm2m_server_add_observer().
Referenced by create_cb(), and registration_cb().
static void registration_cb (void * data, struct sol_lwm2m_server * server, struct sol_lwm2m_client_info * cinfo, enum sol_lwm2m_registration_event event) static
References create_location_obj(), get_location_object_status(), LOCATION_OBJECT_NOT_FOUND, LOCATION_OBJECT_WITH_NO_INSTANCES, observe_location(), sol_lwm2m_client_info_get_name(), SOL_LWM2M_REGISTRATION_EVENT_TIMEOUT, SOL_LWM2M_REGISTRATION_EVENT_UNREGISTER, and SOL_LWM2M_REGISTRATION_EVENT_UPDATE.
Referenced by main().