Soletta: src/samples/coap/lwm2m-client.c File Reference
lwm2m-client.c File Reference
#include "sol-lwm2m.h"
#include "sol-mainloop.h"
#include "sol-vector.h"
#include "sol-util.h"
#include <stdio.h>
#include <stdbool.h>
#include <errno.h>
#include <time.h>
Data Structures
struct location_obj_instance_ctx
Macros
#define LIFETIME (60)
#define LOCATION_OBJ_ID (6)
#define LOCATION_OBJ_LATITUDE_RES_ID (0)
#define LOCATION_OBJ_LONGITUDE_RES_ID (1)
#define LOCATION_OBJ_TIMESTAMP_RES_ID (5)
#define ONE_SECOND (1000)
#define SECURITY_SERVER_IS_BOOTSTRAP_RES_ID (1)
#define SECURITY_SERVER_OBJ_ID (0)
#define SECURITY_SERVER_SERVER_ID_RES_ID (10)
#define SECURITY_SERVER_SERVER_URI_RES_ID (0)
#define SERVER_OBJ_BINDING_RES_ID (7)
#define SERVER_OBJ_ID (1)
#define SERVER_OBJ_LIFETIME_RES_ID (1)
#define SERVER_OBJ_REGISTRATION_UPDATE_RES_ID (8)
#define SERVER_OBJ_SHORT_RES_ID (0)
Functions
static bool change_location (void *data)
static int create_location_obj (void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, void **instance_data, enum sol_lwm2m_content_type content_type, const struct sol_str_slice content)
static int del_location_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id)
static int execute_server_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, uint16_t res_id, const struct sol_str_slice args)
static char * generate_new_coord (void)
int main (int argc, char *argv[])
static int read_location_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource *res)
static int read_security_server_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource *res)
static int read_server_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource *res)
Variables
static const struct
sol_lwm2m_object location_object
static const struct
sol_lwm2m_object security_object
static const struct
sol_lwm2m_object server_object
Macro Definition Documentation
#define LIFETIME (60)
Referenced by read_server_obj().
#define LOCATION_OBJ_ID (6)
#define LOCATION_OBJ_LATITUDE_RES_ID (0)
Referenced by create_location_obj(), and read_location_obj().
#define LOCATION_OBJ_LONGITUDE_RES_ID (1)
Referenced by create_location_obj(), and read_location_obj().
#define LOCATION_OBJ_TIMESTAMP_RES_ID (5)
Referenced by read_location_obj().
#define ONE_SECOND (1000)
Referenced by create_location_obj().
#define SECURITY_SERVER_IS_BOOTSTRAP_RES_ID (1)
Referenced by read_security_server_obj().
#define SECURITY_SERVER_OBJ_ID (0)
#define SECURITY_SERVER_SERVER_ID_RES_ID (10)
Referenced by read_security_server_obj().
#define SECURITY_SERVER_SERVER_URI_RES_ID (0)
Referenced by read_security_server_obj().
#define SERVER_OBJ_BINDING_RES_ID (7)
Referenced by read_server_obj().
#define SERVER_OBJ_ID (1)
#define SERVER_OBJ_LIFETIME_RES_ID (1)
Referenced by read_server_obj().
#define SERVER_OBJ_REGISTRATION_UPDATE_RES_ID (8)
Referenced by execute_server_obj().
#define SERVER_OBJ_SHORT_RES_ID (0)
Referenced by read_server_obj().
Function Documentation
static bool change_location (void * data) static
References location_obj_instance_ctx::client, generate_new_coord(), location_obj_instance_ctx::latitude, location_obj_instance_ctx::longitude, sol_lwm2m_notify_observers(), and location_obj_instance_ctx::timestamp.
Referenced by create_location_obj().
static int create_location_obj (void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, void ** instance_data, enum sol_lwm2m_content_type content_type, const struct sol_str_slice content) static
References change_location(), location_obj_instance_ctx::client, sol_lwm2m_tlv::id, location_obj_instance_ctx::latitude, sol_vector::len, LOCATION_OBJ_LATITUDE_RES_ID, LOCATION_OBJ_LONGITUDE_RES_ID, location_obj_instance_ctx::longitude, ONE_SECOND, SOL_LWM2M_CONTENT_TYPE_TLV, sol_lwm2m_parse_tlv(), sol_lwm2m_tlv_array_clear(), sol_lwm2m_tlv_get_bytes(), sol_lwm2m_tlv_to_int(), sol_timeout_add(), sol_timeout_del(), SOL_VECTOR_FOREACH_IDX, location_obj_instance_ctx::timeout, and location_obj_instance_ctx::timestamp.
static int del_location_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id) static
References location_obj_instance_ctx::latitude, location_obj_instance_ctx::longitude, sol_timeout_del(), and location_obj_instance_ctx::timeout.
static int execute_server_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, uint16_t res_id, const struct sol_str_slice args) static
References SERVER_OBJ_REGISTRATION_UPDATE_RES_ID, and sol_lwm2m_send_update().
static char* generate_new_coord (void) static
Referenced by change_location().
int main (int argc, char * argv[])
References location_object, security_object, server_object, sol_init(), sol_lwm2m_add_object_instance(), sol_lwm2m_client_del(), sol_lwm2m_client_new(), sol_lwm2m_client_start(), sol_lwm2m_client_stop(), sol_run(), and sol_shutdown().
static int read_location_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource * res) static
References location_obj_instance_ctx::latitude, LOCATION_OBJ_LATITUDE_RES_ID, LOCATION_OBJ_LONGITUDE_RES_ID, LOCATION_OBJ_TIMESTAMP_RES_ID, location_obj_instance_ctx::longitude, SOL_LWM2M_RESOURCE_DATA_TYPE_STRING, SOL_LWM2M_RESOURCE_DATA_TYPE_TIME, SOL_LWM2M_RESOURCE_INIT, and location_obj_instance_ctx::timestamp.
static int read_security_server_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource * res) static
References SECURITY_SERVER_IS_BOOTSTRAP_RES_ID, SECURITY_SERVER_SERVER_ID_RES_ID, SECURITY_SERVER_SERVER_URI_RES_ID, SOL_LWM2M_RESOURCE_DATA_TYPE_BOOLEAN, SOL_LWM2M_RESOURCE_DATA_TYPE_INT, SOL_LWM2M_RESOURCE_DATA_TYPE_STRING, and SOL_LWM2M_RESOURCE_INIT.
static int read_server_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource * res) static
References LIFETIME, SERVER_OBJ_BINDING_RES_ID, SERVER_OBJ_LIFETIME_RES_ID, SERVER_OBJ_SHORT_RES_ID, SOL_LWM2M_RESOURCE_DATA_TYPE_INT, SOL_LWM2M_RESOURCE_DATA_TYPE_STRING, and SOL_LWM2M_RESOURCE_INIT.
Variable Documentation
const struct sol_lwm2m_object location_object static
Initial value:
= {
    .id = LOCATION_OBJ_ID,
    .create = create_location_obj,
    .read = read_location_obj,
    .del = del_location_obj,
    .resources_count = 6
}
Referenced by main().
const struct sol_lwm2m_object security_object static
Initial value:
= {
    .id = SECURITY_SERVER_OBJ_ID,
    .resources_count = 12,
    .read = read_security_server_obj
}
Referenced by main().
const struct sol_lwm2m_object server_object static
Initial value:
= {
    .id = SERVER_OBJ_ID,
    .resources_count = 9,
    .read = read_server_obj,
    .execute = execute_server_obj
}
Referenced by main().